import test from 'node:test';
import assert from 'node:assert/strict';
import { buildPlan, planToMarkdown, upgradeHops, existingUiTests } from '../src/plan.js';
import { makeProject } from './helpers.js';
import { htmlReport } from '../src/report-html.js';
import { textReport } from '../src/report-text.js';

test('upgrade hops step roughly three minors at a time', () => {
  assert.deepEqual(upgradeHops('0.77.1', '0.87.1'), ['0.80.0', '0.83.0', '0.86.0', '0.87.1']);
  assert.deepEqual(upgradeHops('0.86.2', '0.87.1'), ['0.87.1']);
});

const result = {
  scannedAt: '2026-10-03T12:00:00.000Z',
  project: { name: '<script>alert(1)</script>', root: '/nonexistent', reactNative: '0.77.1', expo: null, managed: false, newArch: { android: false, ios: false }, android: { targetSdk: 36 } },
  latest: { reactNative: '0.87.1', expo: null },
  offline: false,
  warnings: [],
  deps: [{ name: '@react-native-firebase/messaging', native: true }],
  findings: [
    { id: 'rn-unsupported', severity: 'critical', area: 'react-native', title: 'React Native 0.77.1 is no longer supported', detail: 'x', fix: { kind: 'upgrade-rn', from: '0.77.1', to: '0.87.1' } },
    { id: 'new-arch-disabled', severity: 'critical', area: 'new-architecture', title: 'New Architecture is disabled', detail: 'x', fix: { kind: 'enable-new-arch', platforms: ['android', 'ios'] } },
    { id: 'dep-risk:push', severity: 'high', area: 'dependency', title: 'push: unmaintained', detail: 'x', fix: { kind: 'replace-dep', name: '@react-native-community/push-notification-ios', native: true, noNewArch: true, unmaintained: true, alternatives: ['@react-native-firebase/messaging'] } },
    { id: 'secret:aws', severity: 'critical', area: 'secret', title: 'AWS key', detail: 'x', fix: { kind: 'secret', label: 'AWS access key ID', file: 'src/a.js', line: 3, bundled: true } },
  ],
};

test('plan orders phases: leaks, blockers, architecture, then React Native', () => {
  const plan = buildPlan(result);
  const titles = plan.phases.map((p) => p.title);
  const idx = (s) => titles.findIndex((t) => t.startsWith(s));
  assert.ok(idx('Stop the leaks') === 0);
  assert.equal(idx('Set up a safety net'), 1, 'UI tests come before the first code change');
  assert.ok(idx('Replace blocking') < idx('Turn on the New Architecture'));
  assert.ok(idx('Turn on the New Architecture') < idx('Upgrade React Native'));
  assert.equal(titles.at(-1), 'Verify before you ship');

  const md = planToMarkdown(result, plan);
  assert.match(md, /You already use `@react-native-firebase\/messaging`/, 'does not tell users to install what they already have');
  assert.match(md, /upgrade-helper\/\?from=0\.77\.1&to=0\.80\.0/);
});

test('HTML report escapes project data and supports white-label', () => {
  const html = htmlReport(result, { brand: 'Acme Mobile' });
  assert.ok(!html.includes('<script>alert(1)</script>'));
  assert.match(html, /Prepared by Acme Mobile/);
  assert.ok(!html.includes('Generated by'));
  assert.match(htmlReport(result), /Generated by <a href="https:\/\/nativekeel.com">NativeKeel<\/a>/);
});

test('text report without color has no escape codes', () => {
  const text = textReport(result, { color: false });
  assert.ok(!text.includes('\x1b['));
  assert.match(text, /3 critical/);
});

test('SARIF: valid shape, levels, stable fingerprints, file locations', async () => {
  const { sarifReport } = await import('../src/report-sarif.js');
  const sarif = sarifReport(result, { version: '1.2.3' });
  assert.equal(sarif.version, '2.1.0');
  const run = sarif.runs[0];
  assert.equal(run.tool.driver.name, 'NativeKeel');
  const byId = Object.fromEntries(run.results.map((r) => [r.partialFingerprints.nativekeelId, r]));
  assert.equal(byId['rn-unsupported'].level, 'error');
  assert.deepEqual(byId['secret:aws'].locations[0].physicalLocation, { artifactLocation: { uri: 'src/a.js' }, region: { startLine: 3 } });
  for (const r of run.results) assert.ok(run.tool.driver.rules.some((rule) => rule.id === r.ruleId), `rule ${r.ruleId} is declared`);
});

test('Markdown escapes table cells and summarises counts', async () => {
  const { markdownReport } = await import('../src/report-md.js');
  const md = markdownReport({ ...result, findings: [...result.findings, { id: 'x', severity: 'high', area: 'dependency', title: 'a | b', detail: 'line1\nline2' }] });
  assert.match(md, /🔴 3 critical · 🟠 2 high/);
  assert.match(md, /a \\| b/);
  assert.match(md, /line1 line2/);
});

test('compare: fixed, new, and version changes', async () => {
  const { compareScans, compareToMarkdown } = await import('../src/compare.js');
  const after = {
    ...result,
    scannedAt: '2026-11-03T12:00:00.000Z',
    project: { ...result.project, reactNative: '0.87.1', newArch: { android: true, ios: true } },
    findings: [{ id: 'new-thing', severity: 'high', area: 'dependency', title: 'Something new', detail: '' }],
  };
  const c = compareScans(result, after);
  assert.deepEqual(c.fixed.map((f) => f.id).sort(), ['dep-risk:push', 'new-arch-disabled', 'rn-unsupported', 'secret:aws']);
  assert.deepEqual(c.added.map((f) => f.id), ['new-thing']);
  const md = compareToMarkdown(c);
  assert.match(md, /\| React Native \| 0.77.1 \| 0.87.1 \|/);
  assert.match(md, /\| New Architecture \| off \| on \|/);
  assert.match(md, /✅ React Native 0.77.1 is no longer supported/);
});

test('text report: non-dependency low findings are not hidden under the outdated-packages heading', () => {
  const r = {
    ...result,
    findings: [
      { id: 'dep-major:a', severity: 'low', area: 'dependency', title: 'a 1.0.0 → 2.0.0', detail: 'Major version behind.' },
      { id: 'android-default-react-host', severity: 'low', area: 'native', title: 'MainApplication.java calls getDefaultReactHost', detail: 'Pass null.' },
    ],
  };
  const text = textReport(r, { color: false });
  assert.match(text, /LOW {6}MainApplication.java calls getDefaultReactHost\n {11}Pass null\./);
  assert.match(text, /1 package is a major version behind:\n {11}a 1.0.0 → 2.0.0/);
});

test('safety net: only when the plan changes code', () => {
  const onlySecret = { ...result, findings: result.findings.filter((f) => f.area === 'secret') };
  const titles = buildPlan(onlySecret).phases.map((p) => p.title);
  assert.ok(!titles.includes('Set up a safety net'));
});

test('safety net: uses the UI tests the project already has', () => {
  const maestro = makeProject({ '.maestro/login.yaml': 'appId: com.example\n---\n- launchApp\n', 'package.json': '{}' });
  assert.equal(existingUiTests(maestro, new Set()), 'Maestro');
  assert.equal(existingUiTests(makeProject({ 'package.json': '{}' }), new Set(['detox'])), 'Detox');
  const ciYaml = makeProject({ 'e2e/workflow.yml': 'name: ci\non: push\n' });
  assert.equal(existingUiTests(ciYaml, new Set()), null, 'a YAML file is not a Maestro flow');

  const plan = buildPlan({ ...result, project: { ...result.project, root: maestro } });
  const net = plan.phases.find((p) => p.title === 'Set up a safety net');
  assert.match(net.steps[0], /Run your Maestro suite/);
});

test('Expo plan: SDK-managed packages move with `expo install --fix`, not by hand', () => {
  const expoResult = {
    ...result,
    project: { ...result.project, name: 'e', root: '/nonexistent', reactNative: '0.69.9', expo: '46.0.21', managed: true },
    findings: [
      { id: 'expo-unsupported', severity: 'critical', area: 'expo', title: 'x', detail: 'x', fix: { kind: 'upgrade-expo', from: 46, to: 48 } },
      { id: 'dep-major:expo-file-system', severity: 'low', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'bump-dep', name: 'expo-file-system', from: '14.1.0', to: '57.0.7', native: true } },
      { id: 'dep-major:react-native-reanimated', severity: 'low', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'bump-dep', name: 'react-native-reanimated', from: '2.9.1', to: '4.7.1', native: true } },
      { id: 'dep-major:react-native-blob-util', severity: 'low', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'bump-dep', name: 'react-native-blob-util', from: '0.19.0', to: '0.25.1', native: true } },
      { id: 'dep-risk:expo-av', severity: 'high', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'replace-dep', name: 'expo-av', native: true, unmaintained: true, alternatives: ['expo-audio'] } },
    ],
  };
  const md = planToMarkdown(expoResult, buildPlan(expoResult));
  assert.ok(!/`expo-file-system` 14\.1\.0 → 57/.test(md), 'never bump an Expo package past the SDK');
  assert.ok(!/`react-native-reanimated` 2\.9\.1 → 4/.test(md));
  assert.match(md, /`react-native-blob-util` 0\.19\.0 → 0\.25\.1/, 'packages Expo does not pin are still listed');
  assert.match(md, /`npx expo install --fix` also moves `expo-file-system`, `react-native-reanimated`/);
  assert.match(md, /npx expo install expo-audio/);
});

test('old app: the New Architecture switch goes inside the React Native hops, at 0.76–0.81', () => {
  const old = {
    ...result,
    project: { ...result.project, reactNative: '0.63.4' },
    findings: [
      { id: 'rn-unsupported', severity: 'critical', area: 'react-native', title: 'x', detail: 'x', fix: { kind: 'upgrade-rn', from: '0.63.4', to: '0.87.1' } },
      { id: 'new-arch-disabled', severity: 'critical', area: 'new-architecture', title: 'x', detail: 'x', fix: { kind: 'enable-new-arch', platforms: ['android', 'ios'] } },
    ],
  };
  const plan = buildPlan(old);
  assert.ok(!plan.phases.some((p) => p.title.startsWith('Turn on the New Architecture on your current version')), 'not on 0.63');
  const steps = plan.phases.find((p) => p.title.startsWith('Upgrade React Native')).steps;
  const stop = steps.findIndex((s) => s.startsWith('**Stop at 0.78.0 and turn on the New Architecture**'));
  assert.ok(stop > 0);
  assert.ok(steps[stop - 1].includes('→ 0.78.0'), 'right after reaching 0.78');
  assert.ok(steps[stop + 1].startsWith('New Architecture: '));
});

test('plan: JS-only abandoned packages are not blockers, low notes stay out, 16 KB deadline is explicit', () => {
  const r = {
    ...result,
    findings: [
      { id: 'android-16kb-rn', severity: 'critical', area: 'store', title: 'x', detail: 'x', fix: { kind: 'upgrade-rn-min', to: '0.77.0' } },
      { id: 'rn-unsupported', severity: 'critical', area: 'react-native', title: 'x', detail: 'x', fix: { kind: 'upgrade-rn', from: '0.76.5', to: '0.87.1' } },
      { id: 'dep-risk:crypto-js', severity: 'medium', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'replace-dep', name: 'crypto-js', native: false, noNewArch: false, unmaintained: true, alternatives: [] } },
      { id: 'dep-risk:react-native-track-player', severity: 'high', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'replace-dep', name: 'react-native-track-player', native: true, noNewArch: true, unmaintained: false, alternatives: [] } },
      { id: 'interop-job:react-native-track-player', severity: 'high', area: 'new-architecture', title: 'x', detail: 'x', fix: { kind: 'interop-job', name: 'react-native-track-player', methods: ['play'] } },
      { id: 'known:linear-gradient-interop-unmount', severity: 'low', area: 'dependency', title: 'note', detail: 'x', fix: { kind: 'known-issue', name: 'react-native-linear-gradient', title: 'note', detail: 'x', severity: 'low' } },
    ],
  };
  const plan = buildPlan(r);
  const titles = plan.phases.map((p) => p.title);
  const blockers = plan.phases.find((p) => p.title === 'Replace blocking and abandoned packages');
  assert.ok(!blockers.steps.some((s) => s.includes('crypto-js')));
  assert.ok(titles.includes('Plan replacements for abandoned JavaScript packages'));
  assert.match(blockers.steps.find((s) => s.includes('track-player')), /patches it so it loads/);
  assert.ok(!titles.includes('Avoid known traps'), 'a low note is not a trap');
  assert.ok(plan.phases.find((p) => p.title.startsWith('Meet App Store')).steps.some((s) => s.includes('React Native 0.77 or later')));
});

test('complexity: many routine bumps do not size a current app like a migration', async () => {
  const { complexity } = await import('../src/plan.js');
  const bumps = Array.from({ length: 40 }, (_, i) => ({ fix: { kind: 'bump-dep', native: i % 2 === 0 } }));
  assert.notEqual(complexity(bumps).size, 'Extra large');
  const migration = [{ fix: { kind: 'upgrade-rn', from: '0.70.0', to: '0.87.1' } }, { fix: { kind: 'enable-new-arch' } }, ...bumps];
  assert.ok(['Large', 'Extra large'].includes(complexity(migration).size));
  assert.ok(complexity(migration).score > complexity(bumps).score * 2);
});

test('managed Expo plan: no native-folder commands', () => {
  const managed = {
    ...result,
    project: { ...result.project, reactNative: '0.74.5', expo: '51.0.39', managed: true },
    findings: [
      { id: 'expo-unsupported', severity: 'critical', area: 'expo', title: 'x', detail: 'x', fix: { kind: 'upgrade-expo', from: 51, to: 54 } },
      { id: 'new-arch-disabled', severity: 'critical', area: 'new-architecture', title: 'x', detail: 'x', fix: { kind: 'enable-new-arch', platforms: ['android', 'ios'] } },
    ],
  };
  const md = planToMarkdown(managed, buildPlan(managed));
  assert.ok(!/gradlew|ios\/Pods|Xcode Archive/.test(md), md.match(/.*(gradlew|ios\/Pods|Xcode Archive).*/)?.[0]);
  assert.match(md, /eas build/);
  assert.match(md, /At SDK 52, turn on the New Architecture/);
});

test('reports show what "not set" means for the New Architecture', () => {
  const r = (rn) => ({ ...result, project: { ...result.project, reactNative: rn, newArch: { android: null, ios: null } }, findings: [] });
  assert.match(textReport(r('0.74.5'), { color: false }), /android: off \(default\)/);
  assert.match(textReport(r('0.80.0'), { color: false }), /android: on \(default\)/);
});

test('bare app: prefer a non-Expo replacement, flag Expo-only ones', () => {
  const r = {
    ...result,
    findings: [
      { id: 'dep-risk:rn-fetch-blob', severity: 'high', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'replace-dep', name: 'rn-fetch-blob', native: true, noNewArch: false, unmaintained: true, alternatives: ['expo-file-system', 'react-native-blob-util'] } },
      { id: 'dep-risk:@react-native-community/blur', severity: 'high', area: 'dependency', title: 'x', detail: 'x', fix: { kind: 'replace-dep', name: '@react-native-community/blur', native: true, noNewArch: false, unmaintained: true, alternatives: ['expo-blur'] } },
    ],
  };
  const md = planToMarkdown(r, buildPlan(r));
  assert.match(md, /npm uninstall rn-fetch-blob && npm install react-native-blob-util/);
  assert.match(md, /npm install expo-blur` \(Expo packages need Expo modules first/);
});
