#!/usr/bin/env node
// Prints the react-native-reanimated rows for src/compat.js, generated from Reanimated's own
// compatibility.json (the data its docs table is rendered from). Hand-copying that table went
// wrong in several rows, so regenerate instead of editing:
//   node scripts/reanimated-compat.mjs > /tmp/rows.txt   (then paste into src/compat.js)
const URL = 'https://raw.githubusercontent.com/software-mansion/react-native-reanimated/main/packages/react-native-reanimated/compatibility.json';
const data = await (await fetch(URL)).json();

function rows(arch) {
  const out = [];
  for (const [key, value] of Object.entries(data[arch])) {
    const rn = (value['react-native'] || []).map((v) => Number(v.split('.')[1]));
    if (!rn.length || !/^\d/.test(key)) continue;
    const [a, b = a] = key.split(/\s*-\s*/).map((k) => k.replace(/\.x$/, ''));
    out.push({ from: `${a}.0`, to: `${b}.99`, rnMin: Math.min(...rn), rnMax: Math.max(...rn) });
  }
  return out.sort((x, y) => x.from.localeCompare(y.from, undefined, { numeric: true }));
}

const fmt = (r) => `      { from: '${r.from}', to: '${r.to}', rnMin: ${r.rnMin}, rnMax: ${r.rnMax} },`;
console.log(`    // Generated by scripts/reanimated-compat.mjs on ${new Date().toISOString().slice(0, 10)} from ${URL}`);
console.log('    newArch: [');
rows('fabric').forEach((r) => console.log(fmt(r)));
console.log('    ],');
console.log('    legacy: [');
rows('paper').forEach((r) => console.log(fmt(r)));
console.log("      { from: '4.0.0', unsupported: true },");
console.log('    ],');
