// iOS SDKs on Apple's list that need a privacy manifest (developer.apple.com/support/third-party-SDK-requirements),
// with the first CocoaPods release whose podspec ships one. Regenerate with scripts/privacy-sdk-table.mjs.
// Binary pods whose manifest is inside the framework (Facebook SDK, GoogleSignIn, OneSignal, OpenSSL)
// cannot be checked from the podspec and are left out. Apple's "hermes" is Imgur's 2015 project, not
// React Native's engine (confirmed by the React Native team), so hermes-engine is not listed.
export const PRIVACY_SDKS = {
  'abseil': { sdk: 'Abseil', firstWithManifest: '1.20240116.1' },
  'Alamofire': { sdk: 'Alamofire', firstWithManifest: '5.9.0' },
  'AppAuth': { sdk: 'AppAuth', firstWithManifest: '1.7.0' },
  'BoringSSL-GRPC': { sdk: 'BoringSSL / openssl_grpc', firstWithManifest: '0.0.32' },
  'DGCharts': { sdk: 'Charts', firstWithManifest: '5.1.0' },
  'FMDB': { sdk: 'FMDB', firstWithManifest: '2.7.9' },
  'PromisesObjC': { sdk: 'FBLPromises', firstWithManifest: '2.4.0' },
  'PromisesSwift': { sdk: 'Promises', firstWithManifest: '2.4.0' },
  'FirebaseABTesting': { sdk: 'FirebaseABTesting', firstWithManifest: '10.22.0' },
  'FirebaseAuth': { sdk: 'FirebaseAuth', firstWithManifest: '10.22.0' },
  'FirebaseCore': { sdk: 'FirebaseCore', firstWithManifest: '10.22.0' },
  'FirebaseCoreExtension': { sdk: 'FirebaseCoreExtension', firstWithManifest: '10.22.0' },
  'FirebaseCoreInternal': { sdk: 'FirebaseCoreInternal', firstWithManifest: '10.22.0' },
  'FirebaseCrashlytics': { sdk: 'FirebaseCrashlytics', firstWithManifest: '10.22.0' },
  'FirebaseDynamicLinks': { sdk: 'FirebaseDynamicLinks', firstWithManifest: '10.22.0' },
  'FirebaseFirestore': { sdk: 'FirebaseFirestore', firstWithManifest: '10.22.0' },
  'FirebaseInstallations': { sdk: 'FirebaseInstallations', firstWithManifest: '10.22.0' },
  'FirebaseMessaging': { sdk: 'FirebaseMessaging', firstWithManifest: '10.22.0' },
  'FirebaseRemoteConfig': { sdk: 'FirebaseRemoteConfig', firstWithManifest: '10.22.0' },
  'GoogleDataTransport': { sdk: 'GoogleDataTransport', firstWithManifest: '9.4.0' },
  'GoogleToolboxForMac': { sdk: 'GoogleToolboxForMac', firstWithManifest: '4.2.0' },
  'GoogleUtilities': { sdk: 'GoogleUtilities', firstWithManifest: '7.13.0' },
  'gRPC-C++': { sdk: 'grpcpp', firstWithManifest: '1.61.0' },
  'GTMAppAuth': { sdk: 'GTMAppAuth', firstWithManifest: '4.1.1' },
  'GTMSessionFetcher': { sdk: 'GTMSessionFetcher', firstWithManifest: '3.3.0' },
  'IQKeyboardManager': { sdk: 'IQKeyboardManager', firstWithManifest: '6.5.13' },
  'IQKeyboardManagerSwift': { sdk: 'IQKeyboardManagerSwift', firstWithManifest: '6.5.13' },
  'Kingfisher': { sdk: 'Kingfisher', firstWithManifest: '7.10.0' },
  'leveldb-library': { sdk: 'leveldb', firstWithManifest: '1.22.4' },
  'lottie-ios': { sdk: 'Lottie', firstWithManifest: '4.4.0' },
  'nanopb': { sdk: 'nanopb', firstWithManifest: '2.30910.0' },
  'OrderedSet': { sdk: 'OrderedSet', firstWithManifest: '6.0.3' },
  'Protobuf': { sdk: 'Protobuf', firstWithManifest: '3.25.3' },
  'Reachability': { sdk: 'Reachability', firstWithManifest: '3.7.6' },
  'ReachabilitySwift': { sdk: 'Reachability', firstWithManifest: '5.2.1' },
  'RealmSwift': { sdk: 'RealmSwift', firstWithManifest: '10.46.0' },
  'RxCocoa': { sdk: 'RxCocoa', firstWithManifest: '6.8.0' },
  'RxRelay': { sdk: 'RxRelay', firstWithManifest: '6.8.0' },
  'RxSwift': { sdk: 'RxSwift', firstWithManifest: '6.8.0' },
  'SDWebImage': { sdk: 'SDWebImage', firstWithManifest: '5.18.7' },
  'SnapKit': { sdk: 'SnapKit', firstWithManifest: '5.7.1' },
  'Starscream': { sdk: 'Starscream', firstWithManifest: '4.0.8' },
  'SVProgressHUD': { sdk: 'SVProgressHUD', firstWithManifest: '2.3.0' },
  'SwiftyGif': { sdk: 'SwiftyGif', firstWithManifest: '5.4.5' },
  'SwiftyJSON': { sdk: 'SwiftyJSON', firstWithManifest: '5.0.2' },
  'Toast': { sdk: 'Toast', firstWithManifest: '4.1.0' },
  // Source pods with no release that has a manifest: replace them.
  'AFNetworking': { sdk: 'AFNetworking', firstWithManifest: null },
  'Charts': { sdk: 'Charts', firstWithManifest: null },
  'MBProgressHUD': { sdk: 'MBProgressHUD', firstWithManifest: null },
  'FirebaseCoreDiagnostics': { sdk: 'FirebaseCoreDiagnostics', firstWithManifest: null },
};
