import { SEVERITIES, countBySeverity } from './analyze.js';
import { SITE_URL } from './config.js';
import { startHere } from './plan.js';
import { MASVS_GROUPS } from './security.js';

const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch]);
// Turns `code` spans from finding text into <code>.
const rich = (s) => esc(s).replace(/`([^`]+)`/g, '<code>$1</code>');

// A single self-contained file that can be emailed or attached to a ticket.
// `brand` replaces NativeKeel branding with an agency's name.
export function htmlReport(result, { brand = null, plan = null } = {}) {
  const p = result.project;
  const n = countBySeverity(result.findings);
  const title = `${p.name || 'App'} health report`;
  const sevLabel = { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low', info: 'Info' };
  const defaultOn = !!result.project.reactNative && Number(result.project.reactNative.split('.')[1]) >= 76;
  const arch = (v) => (v === true ? 'on' : v === false ? 'off' : defaultOn ? 'on (default)' : 'off (default)');

  // Outdated packages are many and alike: one collapsible table instead of a card each.
  const isBump = (f) => f.id.startsWith('dep-major:');
  const rows = SEVERITIES.flatMap((sev) =>
    result.findings
      .filter((f) => f.severity === sev && !isBump(f))
      .map((f) => `<li class="f ${sev}"><span class="tag">${sevLabel[sev]}</span><div><strong>${rich(f.title)}</strong><p>${rich(f.detail)}</p></div></li>`),
  ).join('\n');
  const bumps = result.findings.filter(isBump);
  const bumpTable = bumps.length
    ? `<details class="bumps"><summary>${bumps.length} package${bumps.length === 1 ? ' is' : 's are'} a major version behind <span class="muted">(low)</span></summary><table><thead><tr><th>Package</th><th>Installed</th><th>Latest</th><th></th></tr></thead><tbody>${bumps
        .map((f) => `<tr><td>${esc(f.fix.name)}</td><td>${esc(f.fix.from || '')}</td><td>${esc(f.fix.to || '')}</td><td class="muted">${f.fix.native ? 'native' : ''}</td></tr>`)
        .join('')}</tbody></table></details>`
    : '';

  const planHtml = plan
    ? `<section><h2>${plan.phases.some((ph) => /^Upgrade (React Native|Expo SDK)/.test(ph.title)) ? 'Upgrade plan' : 'Action plan'} <small>scope: ${esc(plan.complexity.size)}</small></h2>${plan.phases
        .map((ph, i) => `<h3>${i + 1}. ${esc(ph.title)}</h3><p class="why">${esc(ph.why)}</p><ul>${ph.steps.map((s) => `<li>${rich(s)}</li>`).join('')}</ul>`)
        .join('')}</section>`
    : '';

  const footer = brand
    ? `Prepared by ${esc(brand)} · ${esc(result.scannedAt.slice(0, 10))}`
    : `Generated by <a href="${SITE_URL}">NativeKeel</a> · ${esc(result.scannedAt.slice(0, 10))}`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
:root{--bg:#f7f8fa;--card:#fff;--text:#16181d;--muted:#5f6673;--line:#e3e6eb;--critical:#c62828;--high:#b26a00;--medium:#8a6d00;--low:#6b7280;--info:#1e5fb4;--accent:#0b5d55}
@media (prefers-color-scheme:dark){:root{--bg:#0f1115;--card:#171a20;--text:#e8eaee;--muted:#9aa1ad;--line:#2a2f38;--critical:#ff6b6b;--high:#f0a73a;--medium:#d9c24a;--low:#8b93a1;--info:#6aa7ff;--accent:#3cc4b4}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
main{max-width:860px;margin:0 auto;padding:32px 16px 48px}
h1{font-size:26px;margin:0 0 4px}h2{font-size:19px;margin:32px 0 12px}h2 small{font-weight:400;color:var(--muted);font-size:14px}h3{font-size:16px;margin:20px 0 4px}
.meta{color:var(--muted);margin:0 0 20px}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
.stat{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px}
.stat b{display:block;font-size:24px}.stat span{color:var(--muted);font-size:13px}
.stat.critical b{color:var(--critical)}.stat.high b{color:var(--high)}
.facts{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px 16px;margin-top:12px;display:flex;flex-wrap:wrap;gap:6px 24px;font-size:14px}
ul.list{list-style:none;padding:0;margin:0;display:grid;gap:8px}
.start{background:var(--card);border:1px solid var(--line);border-left:4px solid var(--accent);border-radius:8px;padding:6px 18px 10px;margin-top:20px}.start h2{margin:10px 0 6px}.start li{margin:6px 0}
.secgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.sg{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:10px 12px;display:flex;flex-direction:column}.sg b{font-size:20px}.sg.ok b{color:var(--accent)}.sg.bad b{color:var(--critical)}.sg small{color:var(--muted)}@media (max-width:560px){.secgrid{grid-template-columns:1fr 1fr}}
details.bumps{margin-top:8px;background:var(--card);border:1px solid var(--line);border-left:4px solid var(--low);border-radius:8px;padding:10px 14px}details.bumps summary{cursor:pointer;font-weight:600}details.bumps table{width:100%;border-collapse:collapse;margin-top:10px;font-size:14px}details.bumps th,details.bumps td{text-align:left;padding:4px 8px;border-top:1px solid var(--line)}.muted{color:var(--muted);font-weight:400}
.f{display:flex;gap:12px;background:var(--card);border:1px solid var(--line);border-left:4px solid var(--low);border-radius:8px;padding:10px 14px}
.f p{margin:2px 0 0;color:var(--muted);font-size:14px}.f strong{overflow-wrap:anywhere}
.tag{flex:none;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.03em;min-width:64px;padding-top:2px}
.critical{border-left-color:var(--critical)}.critical .tag{color:var(--critical)}
.high{border-left-color:var(--high)}.high .tag{color:var(--high)}
.medium{border-left-color:var(--medium)}.medium .tag{color:var(--medium)}
.low .tag{color:var(--low)}.info{border-left-color:var(--info)}.info .tag{color:var(--info)}
code{font:13px ui-monospace,SFMono-Regular,Menlo,monospace;background:color-mix(in srgb,var(--line) 60%,transparent);padding:1px 4px;border-radius:4px;overflow-wrap:anywhere}
.why{color:var(--muted);font-style:italic;margin:0 0 6px}
footer{margin-top:40px;color:var(--muted);font-size:13px}a{color:var(--accent)}
@media (max-width:560px){.stats{grid-template-columns:repeat(2,1fr)}.f{flex-direction:column;gap:4px}}
</style>
</head>
<body><main>
<h1>${esc(title)}</h1>
<p class="meta">Scanned ${esc(result.scannedAt.slice(0, 16).replace('T', ' '))} UTC</p>
<div class="stats">
<div class="stat critical"><b>${n.critical}</b><span>critical</span></div>
<div class="stat high"><b>${n.high}</b><span>high</span></div>
<div class="stat"><b>${n.medium}</b><span>medium</span></div>
<div class="stat"><b>${n.low}</b><span>low</span></div>
</div>
<div class="facts">
${p.reactNative ? `<span>React Native <b>${esc(p.reactNative)}</b>${result.latest.reactNative ? ` (latest ${esc(result.latest.reactNative)})` : ''}</span>` : ''}
${p.expo ? `<span>Expo SDK <b>${esc(p.expo.split('.')[0])}</b></span>` : ''}
<span>New Architecture: Android <b>${arch(p.newArch.android)}</b>, iOS <b>${arch(p.newArch.ios)}</b></span>
${p.android && p.android.targetSdk ? `<span>targetSdk <b>${p.android.targetSdk}</b></span>` : ''}
<span>${result.deps.length} dependencies (${result.deps.filter((d) => d.native).length} native)</span>
</div>
${n.critical + n.high > 0 ? `<section class="start"><h2>Start here</h2><ol>${startHere(result).map((x) => `<li>${rich(x.step)} <span class="muted">(${esc(x.phase)})</span></li>`).join('')}</ol><p class="muted">The full, ordered plan: <code>npx nativekeel plan</code>.</p></section>` : ''}
${result.security ? `<section class="sec"><h2>Security <small>OWASP MASVS</small></h2><div class="secgrid">${Object.entries(MASVS_GROUPS)
  .map(([g, label]) => `<div class="sg ${result.security[g] ? 'bad' : 'ok'}"><b>${result.security[g] ? result.security[g] : '✓'}</b><span>${esc(label)}</span><small>MASVS-${g}</small></div>`)
  .join('')}</div><p class="muted">Static checks of code, config and dependencies. They find the common, detectable mistakes; they do not replace a penetration test of the running app and its backend.</p></section>` : ''}
<h2>Findings</h2>
${result.findings.length ? `${rows ? `<ul class="list">${rows}</ul>` : ''}${bumpTable}` : '<p>No issues found.</p>'}
${planHtml}
<footer>${footer}</footer>
</main></body></html>
`;
}
