import { SEVERITIES, countBySeverity } from './analyze.js';
import { SITE_URL } from './config.js';

// Markdown for pull request comments and issue trackers.
const ICON = { critical: '🔴', high: '🟠', medium: '🟡', low: '⚪', info: 'ℹ️' };
const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function markdownReport(result, { verbose = false } = {}) {
  const p = result.project;
  const n = countBySeverity(result.findings);
  const lines = [
    `### NativeKeel health report${p.name ? `: ${p.name}` : ''}`,
    '',
    [
      p.reactNative && `React Native **${p.reactNative}**${result.latest.reactNative ? ` (latest ${result.latest.reactNative})` : ''}`,
      p.expo && `Expo SDK **${p.expo.split('.')[0]}**`,
      `New Architecture: Android ${p.newArch.android === false ? '**off**' : p.newArch.android ? 'on' : 'default'}, iOS ${p.newArch.ios === false ? '**off**' : p.newArch.ios ? 'on' : 'default'}`,
    ].filter(Boolean).join(' · '),
    '',
    `${ICON.critical} ${n.critical} critical · ${ICON.high} ${n.high} high · ${ICON.medium} ${n.medium} medium · ${ICON.low} ${n.low} low`,
    '',
  ];

  const main = result.findings.filter((f) => ['critical', 'high', 'medium'].includes(f.severity));
  if (main.length) {
    lines.push('| | Finding | Details |', '|---|---|---|');
    for (const sev of SEVERITIES) {
      for (const f of main.filter((x) => x.severity === sev)) lines.push(`| ${ICON[sev]} | ${cell(f.title)} | ${cell(f.detail)} |`);
    }
    lines.push('');
  }
  const low = result.findings.filter((f) => f.severity === 'low');
  if (low.length) {
    lines.push(`<details><summary>${low.length} low-priority findings</summary>`, '');
    for (const f of verbose ? low : low.slice(0, 50)) lines.push(`- ${f.title}`);
    if (!verbose && low.length > 50) lines.push(`- … and ${low.length - 50} more`);
    lines.push('', '</details>', '');
  }
  if (!result.findings.some((f) => f.severity !== 'info')) lines.push('✅ Nothing to fix.', '');
  lines.push(`<sub>Generated by [NativeKeel](${SITE_URL}) · \`npx nativekeel plan\` for a step-by-step upgrade plan</sub>`);
  return `${lines.join('\n')}\n`;
}
